spring.application.name=SmartBudget

spring.datasource.url=jdbc:mysql://localhost:3306/smart_budget
spring.datasource.username=root
spring.datasource.password=Nandini@9492

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
